In [13]:
import requests 
import json
import pandas as pd

In [14]:
url="https://open.er-api.com/v6/latest/EUR"

In [15]:
# 1) Appel de l'API
response = requests.get(url)

# 2) Conversion de la reponse en dictionnaire Python
data = response.json()

# 3) Recuperer tous les taux
rates = data["rates"]

# 4) Afficher seulement les taux qui nous interessent
print("USD :", rates["USD"])
print("GBP :", rates["GBP"])
print("XOF :", rates["XOF"])

USD : 1.172367
GBP : 0.867715
XOF : 655.957

In [16]:
data

{'result': 'success',
 'provider': 'https://www.exchangerate-api.com',
 'documentation': 'https://www.exchangerate-api.com/docs/free',
 'terms_of_use': 'https://www.exchangerate-api.com/terms',
 'time_last_update_unix': 1776902551,
 'time_last_update_utc': 'Thu, 23 Apr 2026 00:02:31 +0000',
 'time_next_update_unix': 1776989261,
 'time_next_update_utc': 'Fri, 24 Apr 2026 00:07:41 +0000',
 'time_eol_unix': 0,
 'base_code': 'EUR',
 'rates': {'EUR': 1,
  'AED': 4.305495,
  'AFN': 74.932572,
  'ALL': 95.54213,
  'AMD': 437.915855,
  'ANG': 2.098526,
  'AOA': 1101.835498,
  'ARS': 1615.660562,
  'AUD': 1.637845,
  'AWG': 2.098526,
  'AZN': 1.996659,
  'BAM': 1.95583,
  'BBD': 2.344721,
  'BDT': 143.834326,
  'BGN': 1.95583,
  'BHD': 0.440808,
  'BIF': 3501.2698,
  'BMD': 1.172361,
  'BND': 1.494276,
  'BOB': 8.131284,
  'BRL': 5.826758,
  'BSD': 1.172361,
  'BTN': 109.977634,
  'BWP': 16.454766,
  'BYN': 3.297985,
  'BZD': 2.344721,
  'CAD': 1.601064,
  'CDF': 2725.666667,
  'CHF': 0.918196,
  'CLF': 0.026533,
  'CLP': 1048.764345,
  'CNH': 8.001561,
  'CNY': 8.012012,
  'COP': 4200.532746,
  'CRC': 534.714936,
  'CUP': 28.136657,
  'CVE': 110.265,
  'CZK': 24.348053,
  'DJF': 208.35312,
  'DKK': 7.463326,
  'DOP': 70.699894,
  'DZD': 155.352599,
  'EGP': 60.945678,
  'ERN': 17.585411,
  'ETB': 184.269684,
  'FJD': 2.569761,
  'FKP': 0.867713,
  'FOK': 7.463325,
  'GBP': 0.867715,
  'GEL': 3.160315,
  'GGP': 0.867713,
  'GHS': 13.090053,
  'GIP': 0.867713,
  'GMD': 87.092403,
  'GNF': 10311.690705,
  'GTQ': 8.975665,
  'GYD': 245.589078,
  'HKD': 9.177179,
  'HNL': 31.205219,
  'HRK': 7.5345,
  'HTG': 153.689876,
  'HUF': 364.441333,
  'IDR': 20092.548469,
  'ILS': 3.518548,
  'IMP': 0.867713,
  'INR': 109.91122,
  'IQD': 1537.555556,
  'IRR': 1138897.246339,
  'ISK': 143.798371,
  'JEP': 0.867713,
  'JMD': 186.34682,
  'JOD': 0.831204,
  'JPY': 186.804891,
  'KES': 151.684907,
  'KGS': 102.905224,
  'KHR': 4672.571429,
  'KID': 1.637842,
  'KMF': 491.96775,
  'KRW': 1734.229772,
  'KWD': 0.360717,
  'KYD': 0.976967,
  'KZT': 543.359635,
  'LAK': 25836.290133,
  'LBP': 104926.284853,
  'LKR': 371.336952,
  'LRD': 216.20971,
  'LSL': 19.296034,
  'LYD': 7.423973,
  'MAD': 10.848328,
  'MDL': 20.213446,
  'MGA': 4821.663737,
  'MKD': 61.695,
  'MMK': 2465.69828,
  'MNT': 4218.210607,
  'MOP': 9.45616,
  'MRU': 46.865703,
  'MUR': 54.547846,
  'MVR': 18.1566,
  'MWK': 2045.682312,
  'MXN': 20.307729,
  'MYR': 4.635899,
  'MZN': 74.896748,
  'NAD': 19.296034,
  'NGN': 1588.243887,
  'NIO': 43.222851,
  'NOK': 10.893978,
  'NPR': 175.964214,
  'NZD': 1.983842,
  'OMR': 0.450769,
  'PAB': 1.172361,
  'PEN': 4.033686,
  'PGK': 5.1608,
  'PHP': 70.518821,
  'PKR': 326.6877,
  'PLN': 4.244421,
  'PYG': 7426.742719,
  'QAR': 4.267393,
  'RON': 5.094678,
  'RSD': 117.362437,
  'RUB': 87.992083,
  'RWF': 1710.92071,
  'SAR': 4.396353,
  'SBD': 9.316153,
  'SCR': 17.397217,
  'SDG': 525.237956,
  'SEK': 10.780077,
  'SGD': 1.494277,
  'SHP': 0.867713,
  'SLE': 28.922356,
  'SLL': 28922.32563,
  'SOS': 671.246269,
  'SRD': 43.99462,
  'SSP': 5420.201727,
  'STN': 24.5,
  'SYP': 131.900741,
  'SZL': 19.296034,
  'THB': 37.778371,
  'TJS': 11.104306,
  'TMT': 4.112638,
  'TND': 3.381237,
  'TOP': 2.801211,
  'TRY': 52.671434,
  'TTD': 8.220435,
  'TVD': 1.637842,
  'TWD': 36.9543,
  'TZS': 3085.115497,
  'UAH': 51.625156,
  'UGX': 4344.213961,
  'USD': 1.172367,
  'UYU': 46.720883,
  'UZS': 14219.555313,
  'VES': 567.013357,
  'VND': 30575.609727,
  'VUV': 138.230585,
  'WST': 3.153622,
  'XAF': 655.957,
  'XCD': 3.165374,
  'XCG': 2.098526,
  'XDR': 0.8567,
  'XOF': 655.957,
  'XPF': 119.332,
  'YER': 280.261998,
  'ZAR': 19.296048,
  'ZMW': 22.363198,
  'ZWG': 29.6209,
  'ZWL': 29.6209}}

In [17]:
# Utiliser les taux valides issus du bloc securise (API ou fallback)
rates

{'EUR': 1,
 'AED': 4.305495,
 'AFN': 74.932572,
 'ALL': 95.54213,
 'AMD': 437.915855,
 'ANG': 2.098526,
 'AOA': 1101.835498,
 'ARS': 1615.660562,
 'AUD': 1.637845,
 'AWG': 2.098526,
 'AZN': 1.996659,
 'BAM': 1.95583,
 'BBD': 2.344721,
 'BDT': 143.834326,
 'BGN': 1.95583,
 'BHD': 0.440808,
 'BIF': 3501.2698,
 'BMD': 1.172361,
 'BND': 1.494276,
 'BOB': 8.131284,
 'BRL': 5.826758,
 'BSD': 1.172361,
 'BTN': 109.977634,
 'BWP': 16.454766,
 'BYN': 3.297985,
 'BZD': 2.344721,
 'CAD': 1.601064,
 'CDF': 2725.666667,
 'CHF': 0.918196,
 'CLF': 0.026533,
 'CLP': 1048.764345,
 'CNH': 8.001561,
 'CNY': 8.012012,
 'COP': 4200.532746,
 'CRC': 534.714936,
 'CUP': 28.136657,
 'CVE': 110.265,
 'CZK': 24.348053,
 'DJF': 208.35312,
 'DKK': 7.463326,
 'DOP': 70.699894,
 'DZD': 155.352599,
 'EGP': 60.945678,
 'ERN': 17.585411,
 'ETB': 184.269684,
 'FJD': 2.569761,
 'FKP': 0.867713,
 'FOK': 7.463325,
 'GBP': 0.867715,
 'GEL': 3.160315,
 'GGP': 0.867713,
 'GHS': 13.090053,
 'GIP': 0.867713,
 'GMD': 87.092403,
 'GNF': 10311.690705,
 'GTQ': 8.975665,
 'GYD': 245.589078,
 'HKD': 9.177179,
 'HNL': 31.205219,
 'HRK': 7.5345,
 'HTG': 153.689876,
 'HUF': 364.441333,
 'IDR': 20092.548469,
 'ILS': 3.518548,
 'IMP': 0.867713,
 'INR': 109.91122,
 'IQD': 1537.555556,
 'IRR': 1138897.246339,
 'ISK': 143.798371,
 'JEP': 0.867713,
 'JMD': 186.34682,
 'JOD': 0.831204,
 'JPY': 186.804891,
 'KES': 151.684907,
 'KGS': 102.905224,
 'KHR': 4672.571429,
 'KID': 1.637842,
 'KMF': 491.96775,
 'KRW': 1734.229772,
 'KWD': 0.360717,
 'KYD': 0.976967,
 'KZT': 543.359635,
 'LAK': 25836.290133,
 'LBP': 104926.284853,
 'LKR': 371.336952,
 'LRD': 216.20971,
 'LSL': 19.296034,
 'LYD': 7.423973,
 'MAD': 10.848328,
 'MDL': 20.213446,
 'MGA': 4821.663737,
 'MKD': 61.695,
 'MMK': 2465.69828,
 'MNT': 4218.210607,
 'MOP': 9.45616,
 'MRU': 46.865703,
 'MUR': 54.547846,
 'MVR': 18.1566,
 'MWK': 2045.682312,
 'MXN': 20.307729,
 'MYR': 4.635899,
 'MZN': 74.896748,
 'NAD': 19.296034,
 'NGN': 1588.243887,
 'NIO': 43.222851,
 'NOK': 10.893978,
 'NPR': 175.964214,
 'NZD': 1.983842,
 'OMR': 0.450769,
 'PAB': 1.172361,
 'PEN': 4.033686,
 'PGK': 5.1608,
 'PHP': 70.518821,
 'PKR': 326.6877,
 'PLN': 4.244421,
 'PYG': 7426.742719,
 'QAR': 4.267393,
 'RON': 5.094678,
 'RSD': 117.362437,
 'RUB': 87.992083,
 'RWF': 1710.92071,
 'SAR': 4.396353,
 'SBD': 9.316153,
 'SCR': 17.397217,
 'SDG': 525.237956,
 'SEK': 10.780077,
 'SGD': 1.494277,
 'SHP': 0.867713,
 'SLE': 28.922356,
 'SLL': 28922.32563,
 'SOS': 671.246269,
 'SRD': 43.99462,
 'SSP': 5420.201727,
 'STN': 24.5,
 'SYP': 131.900741,
 'SZL': 19.296034,
 'THB': 37.778371,
 'TJS': 11.104306,
 'TMT': 4.112638,
 'TND': 3.381237,
 'TOP': 2.801211,
 'TRY': 52.671434,
 'TTD': 8.220435,
 'TVD': 1.637842,
 'TWD': 36.9543,
 'TZS': 3085.115497,
 'UAH': 51.625156,
 'UGX': 4344.213961,
 'USD': 1.172367,
 'UYU': 46.720883,
 'UZS': 14219.555313,
 'VES': 567.013357,
 'VND': 30575.609727,
 'VUV': 138.230585,
 'WST': 3.153622,
 'XAF': 655.957,
 'XCD': 3.165374,
 'XCG': 2.098526,
 'XDR': 0.8567,
 'XOF': 655.957,
 'XPF': 119.332,
 'YER': 280.261998,
 'ZAR': 19.296048,
 'ZMW': 22.363198,
 'ZWG': 29.6209,
 'ZWL': 29.6209}

In [18]:
clients = pd.read_csv('data/raw/client.csv')
clients

,id,nom,email,city,pays,date_inscription
0,1,Marc Lacroix-Seguin,marc.seguin5862@shopflow.com,La Plata,Argentine,2025-08-13
1,2,Roger Perrot,roger.perrot9726@shopflow.com,Los Angeles,Etats-Unis,2026-02-27
2,3,Simone Marin du Clément,simone.clement8102@shopflow.com,Kyoto,Japon,2025-08-19
3,4,Léon Imbert,leon.imbert2512@shopflow.com,Buenos Aires,Argentine,2025-08-13
4,5,Bernard Lopez-Perrot,bernard.perrot3663@shopflow.com,Tanger,Maroc,2025-06-13
...,...,...,...,...,...,...
195,196,Alfred Rocher,alfred.rocher3407@shopflow.com,Christchurch,Nouvelle-Zelande,2025-06-21
196,197,Martin de la Jacques,martin.jacques401@shopflow.com,Sydney,Australie,2026-02-27
197,198,Nicole Delaunay,NaN,Cologne,Allemagne,2025-11-15
198,199,Françoise Lefort,francoise.lefort8489@shopflow.com,Shanghai,Chine,2026-02-15
199,200,Constance Ollivier,@shopflow.com,NaN,Bresil,2025-10-15

In [19]:
COUNTRY_CURRENCY = {
    "France": "EUR",
    "Allemagne": "EUR",
    "Canada": "CAD",
    "Etats-Unis": "USD",
    "Bresil": "BRL",
    "Argentine": "ARS",
    "Maroc": "MAD",
    "Egypte": "EGP",
    "Nigeria": "NGN",
    "Afrique du Sud": "ZAR",
    "Kenya": "KES",
    "Japon": "JPY",
    "Chine": "CNY",
    "Inde": "INR",
    "Coree du Sud": "KRW",
    "Indonesie": "IDR",
    "Australie": "AUD",
    "Nouvelle-Zelande": "NZD",
    "Mexique": "MXN",
    "Turquie": "TRY"
}

# Version simple : on prend la devise directement depuis le pays
clients['Devise'] = clients['pays'].map(COUNTRY_CURRENCY)

# Si le pays n'est pas dans le dictionnaire, on met UNK
clients['Devise'] = clients['Devise'].fillna('UNK')

clients[['city', 'pays', 'Devise']]

             city              pays Devise
0        La Plata         Argentine    ARS
1     Los Angeles        Etats-Unis    USD
2           Kyoto             Japon    JPY
3    Buenos Aires         Argentine    ARS
4          Tanger             Maroc    MAD
..            ...               ...    ...
195  Christchurch  Nouvelle-Zelande    NZD
196        Sydney         Australie    AUD
197       Cologne         Allemagne    EUR
198      Shanghai             Chine    CNY
199           NaN            Bresil    BRL

[200 rows x 3 columns]

In [20]:
commandes = pd.read_csv('data/raw/commande.csv')
commandes

,id,client_id,produit_id,quantité,total_eur,status,date_commande
0,1,179,47,5.0,2.211942e+06,pending,2025-12-23
1,2,3,18,1.0,2.268010e+05,completed,2025-10-08
2,3,20,39,2.0,2.143343e+06,refunded,2025-09-22
3,4,16,38,3.0,3.806314e+05,completed,2025-07-05
4,5,95,37,5.0,2.249981e+06,completed,2025-08-06
...,...,...,...,...,...,...,...
1010,1011,65,4,1.0,2.491717e+06,cancelled,2025-10-08
1011,1012,193,21,5.0,2.032689e+05,completed,2025-10-01
1012,1013,154,12,3.0,2.579303e+06,completed,2025-07-22
1013,1014,141,16,2.0,1.699981e+06,completed,2025-07-03
1014,1015,92,32,4.0,2.152720e+06,cancelled,2025-07-03

In [21]:
usd_rate = rates.get('USD', 1.0)
commandes['total_usd'] = commandes['total_eur'] * usd_rate
commandes

,id,client_id,produit_id,quantité,total_eur,status,date_commande,total_usd
0,1,179,47,5.0,2.211942e+06,pending,2025-12-23,2.593207e+06
1,2,3,18,1.0,2.268010e+05,completed,2025-10-08,2.658940e+05
2,3,20,39,2.0,2.143343e+06,refunded,2025-09-22,2.512784e+06
3,4,16,38,3.0,3.806314e+05,completed,2025-07-05,4.462398e+05
4,5,95,37,5.0,2.249981e+06,completed,2025-08-06,2.637804e+06
...,...,...,...,...,...,...,...,...
1010,1011,65,4,1.0,2.491717e+06,cancelled,2025-10-08,2.921207e+06
1011,1012,193,21,5.0,2.032689e+05,completed,2025-10-01,2.383058e+05
1012,1013,154,12,3.0,2.579303e+06,completed,2025-07-22,3.023890e+06
1013,1014,141,16,2.0,1.699981e+06,completed,2025-07-03,1.993002e+06
1014,1015,92,32,4.0,2.152720e+06,cancelled,2025-07-03,2.523778e+06

In [22]:
# 1) Nettoyer les colonnes pour eviter les erreurs si on relance la cellule
commandes = commandes.drop(columns=['Devise', 'fx_rate_local', 'total_local', 'id'], errors='ignore')

# 2) Prendre seulement id + devise dans clients
table_devise = clients[['id', 'Devise']]

# 3) Ajouter la devise dans commandes (grace au client_id)
commandes = commandes.merge(table_devise, left_on='client_id', right_on='id', how='left')

# 4) Si devise manquante, mettre UNK
commandes['Devise'] = commandes['Devise'].fillna('UNK')

# 5) Supprimer la colonne id ajoutee par le merge
commandes = commandes.drop(columns=['id'])

# 6) Preparer les taux
rates_local = rates.copy()
rates_local['EUR'] = 1.0

# 7) Ajouter le taux selon la devise
commandes['fx_rate_local'] = commandes['Devise'].map(rates_local).fillna(1.0)

# 8) Calculer le montant local
commandes['total_local'] = commandes['total_eur'] * commandes['fx_rate_local']

# 9) Afficher un apercu
commandes[['client_id', 'Devise', 'total_eur', 'fx_rate_local', 'total_local']].head()

   client_id Devise     total_eur  fx_rate_local   total_local
0        179    ZAR  2.211942e+06      19.296048  4.268173e+07
1          3    JPY  2.268010e+05     186.804891  4.236753e+07
2         20    MAD  2.143343e+06      10.848328  2.325168e+07
3         16    KES  3.806314e+05     151.684907  5.773605e+07
4         95    CNY  2.249981e+06       8.012012  1.802688e+07

In [23]:
commandes[commandes['Devise']=="AUD"]

,client_id,produit_id,quantité,total_eur,status,date_commande,total_usd,Devise,fx_rate_local,total_local
32,139,49,3.0,1.445407e+06,pending,2025-11-27,1.694547e+06,AUD,1.637845,2.367352e+06
45,157,44,1.0,3.956283e+05,pending,2025-09-10,4.638216e+05,AUD,1.637845,6.479778e+05
54,157,37,5.0,9.953648e+05,completed,2025-09-20,1.166933e+06,AUD,1.637845,1.630253e+06
55,157,19,3.0,1.917283e+06,completed,2025-10-02,2.247760e+06,AUD,1.637845,3.140213e+06
71,108,42,1.0,9.011175e+04,cancelled,2025-09-28,1.056440e+05,AUD,1.637845,1.475891e+05
...,...,...,...,...,...,...,...,...,...,...
969,58,3,4.0,8.882913e+05,completed,2025-08-21,1.041403e+06,AUD,1.637845,1.454883e+06
973,134,42,4.0,1.031612e+05,completed,2025-10-23,1.209427e+05,AUD,1.637845,1.689620e+05
983,197,11,3.0,2.366559e+06,pending,2025-07-15,2.774476e+06,AUD,1.637845,3.876058e+06
999,134,43,NaN,1.831169e+06,completed,2025-08-05,2.146802e+06,AUD,1.637845,2.999171e+06
1013,141,16,2.0,1.699981e+06,completed,2025-07-03,1.993002e+06,AUD,1.637845,2.784306e+06